// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:api_consume_and_persistence/model/coordinates.dart';
import 'package:api_consume_and_persistence/model/dob.dart';
import 'package:api_consume_and_persistence/model/location.dart';
import 'package:api_consume_and_persistence/model/login.dart';
import 'package:api_consume_and_persistence/model/picture.dart';
import 'package:api_consume_and_persistence/model/random_user.dart';
import 'package:api_consume_and_persistence/model/registered.dart';
import 'package:api_consume_and_persistence/model/street.dart';
import 'package:api_consume_and_persistence/model/user_id.dart';
import 'package:api_consume_and_persistence/model/user_name.dart';
import 'package:api_consume_and_persistence/model/user_timezone.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CoordinatesAdapter());
    registerAdapter(DobAdapter());
    registerAdapter(LocationAdapter());
    registerAdapter(LoginAdapter());
    registerAdapter(PictureAdapter());
    registerAdapter(RandomUserAdapter());
    registerAdapter(RegisteredAdapter());
    registerAdapter(StreetAdapter());
    registerAdapter(UserIdAdapter());
    registerAdapter(UserNameAdapter());
    registerAdapter(UserTimezoneAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CoordinatesAdapter());
    registerAdapter(DobAdapter());
    registerAdapter(LocationAdapter());
    registerAdapter(LoginAdapter());
    registerAdapter(PictureAdapter());
    registerAdapter(RandomUserAdapter());
    registerAdapter(RegisteredAdapter());
    registerAdapter(StreetAdapter());
    registerAdapter(UserIdAdapter());
    registerAdapter(UserNameAdapter());
    registerAdapter(UserTimezoneAdapter());
  }
}
